# Generated by Django 3.2.5 on 2021-07-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
